version: "3.8"
services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - CHROMA_SERVER_AUTHN_CREDENTIALS=admin:admin
      - CHROMA_SERVER_AUTHN_PROVIDER=token
      - CHROMA_SERVER_AUTHN_CREDENTIALS_PROVIDER=admin:admin
      - IS_PERSISTENT=TRUE

volumes:
  chroma-data:
